#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-eventmachine
Version  : 1.2.0.1
Release  : 5
URL      : https://rubygems.org/downloads/eventmachine-1.2.0.1.gem
Source0  : https://rubygems.org/downloads/eventmachine-1.2.0.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Ruby
Requires: rubygem-eventmachine-lib
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
# About EventMachine  [![Code Climate](https://codeclimate.com/github/eventmachine/eventmachine.svg)](https://codeclimate.com/github/eventmachine/eventmachine)

%package lib
Summary: lib components for the rubygem-eventmachine package.
Group: Libraries

%description lib
lib components for the rubygem-eventmachine package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n eventmachine-1.2.0.1
gem spec %{SOURCE0} -l --ruby > rubygem-eventmachine.gemspec

%build
gem build rubygem-eventmachine.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
eventmachine-1.2.0.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/eventmachine-1.2.0.1
ruby -v -I.:lib:tests test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/eventmachine-1.2.0.1.gem
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/eventmachine-1.2.0.1/gem.build_complete
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/eventmachine-1.2.0.1/gem_make.out
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/eventmachine-1.2.0.1/mkmf.log
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/GNU
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/DocumentationGuidesIndex.md
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/GettingStarted.md
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/old/ChangeLog
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/old/DEFERRABLES
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/old/EPOLL
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/old/INSTALL
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/old/KEYBOARD
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/old/LEGAL
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/old/LIGHTWEIGHT_CONCURRENCY
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/old/PURE_RUBY
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/old/RELEASE_NOTES
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/old/SMTP
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/old/SPAWNED_PROCESSES
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/docs/old/TODO
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/examples/guides/getting_started/01_eventmachine_echo_server.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/examples/guides/getting_started/02_eventmachine_echo_server_that_recognizes_exit_command.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/examples/guides/getting_started/03_simple_chat_server.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/examples/guides/getting_started/04_simple_chat_server_step_one.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/examples/guides/getting_started/05_simple_chat_server_step_two.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/examples/guides/getting_started/06_simple_chat_server_step_three.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/examples/guides/getting_started/07_simple_chat_server_step_four.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/examples/guides/getting_started/08_simple_chat_server_step_five.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/examples/old/ex_channel.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/examples/old/ex_queue.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/examples/old/ex_tick_loop_array.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/examples/old/ex_tick_loop_counter.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/examples/old/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/.RUBYARCHDIR.time
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/binder.cpp
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/binder.h
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/binder.o
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/cmain.cpp
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/cmain.o
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/ed.cpp
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/ed.h
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/ed.o
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/em.cpp
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/em.h
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/em.o
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/eventmachine.h
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/fastfilereader/.RUBYARCHDIR.time
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/fastfilereader/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/fastfilereader/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/fastfilereader/mapper.cpp
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/fastfilereader/mapper.h
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/fastfilereader/mapper.o
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/fastfilereader/rubymain.cpp
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/fastfilereader/rubymain.o
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/kb.cpp
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/kb.o
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/page.cpp
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/page.h
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/page.o
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/pipe.cpp
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/pipe.o
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/project.h
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/rubymain.cpp
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/rubymain.o
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/ssl.cpp
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/ssl.h
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/ssl.o
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/java/.classpath
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/java/.project
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/java/src/com/rubyeventmachine/EmReactor.java
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/java/src/com/rubyeventmachine/EmReactorException.java
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/java/src/com/rubyeventmachine/EventableChannel.java
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/java/src/com/rubyeventmachine/EventableDatagramChannel.java
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/java/src/com/rubyeventmachine/EventableSocketChannel.java
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/buftok.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/callback.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/channel.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/completion.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/deferrable.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/deferrable/pool.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/file_watch.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/future.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/iterator.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/messages.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/pool.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/process_watch.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/processes.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/header_and_content.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/httpclient.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/httpclient2.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/line_and_text.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/line_protocol.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/linetext2.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/memcache.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/object_protocol.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/postgres3.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/saslauth.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/smtpclient.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/smtpserver.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/socks4.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/stomp.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/protocols/tcptest.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/pure_ruby.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/queue.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/resolver.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/spawnable.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/streamer.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/threaded_resource.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/tick_loop.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/timers.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/jeventmachine.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/rakelib/package.rake
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/rakelib/test.rake
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/client.crt
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/client.key
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/dhparam.pem
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/em_test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_attach.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_basic.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_channel.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_completion.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_connection_count.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_connection_write.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_defer.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_deferrable.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_epoll.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_error_handler.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_exc.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_file_watch.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_fork.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_futures.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_get_sock_opt.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_handler_check.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_hc.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_httpclient.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_httpclient2.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_idle_connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_inactivity_timeout.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_ipv4.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_ipv6.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_iterator.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_kb.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_line_protocol.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_ltp.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_ltp2.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_many_fds.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_next_tick.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_object_protocol.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_pause.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_pending_connect_timeout.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_pool.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_process_watch.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_processes.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_proxy_connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_pure.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_queue.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_resolver.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_running.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_sasl.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_send_file.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_servers.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_set_sock_opt.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_shutdown_hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_smtpclient.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_smtpserver.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_spawn.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_ssl_args.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_ssl_dhparam.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_ssl_ecdh_curve.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_ssl_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_ssl_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_ssl_protocols.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_ssl_verify.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_stomp.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_system.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_threaded_resource.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_tick_loop.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_timers.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_ud.rb
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/tests/test_unbind_reason.rb
/usr/lib64/ruby/gems/2.3.0/specifications/eventmachine-1.2.0.1.gemspec

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/eventmachine-1.2.0.1/fastfilereaderext.so
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/eventmachine-1.2.0.1/rubyeventmachine.so
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/fastfilereader/fastfilereaderext.so
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/ext/rubyeventmachine.so
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/fastfilereaderext.so
/usr/lib64/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/rubyeventmachine.so
